#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Darili")]
public partial class CommentDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertEvent_Comments(Event_Comments instance);
  partial void UpdateEvent_Comments(Event_Comments instance);
  partial void DeleteEvent_Comments(Event_Comments instance);
  #endregion
	
	public CommentDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["416ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public CommentDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CommentDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CommentDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public CommentDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Event_Comments> Event_Comments
	{
		get
		{
			return this.GetTable<Event_Comments>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Event_Comments")]
public partial class Event_Comments : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _Comment_Detail;
	
	private int _Comment_EventId;
	
	private int _Comment_Maker;
	
	private System.DateTime _Comment_PublishTime;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnComment_DetailChanging(string value);
    partial void OnComment_DetailChanged();
    partial void OnComment_EventIdChanging(int value);
    partial void OnComment_EventIdChanged();
    partial void OnComment_MakerChanging(int value);
    partial void OnComment_MakerChanged();
    partial void OnComment_PublishTimeChanging(System.DateTime value);
    partial void OnComment_PublishTimeChanged();
    #endregion
	
	public Event_Comments()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_Detail", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
	public string Comment_Detail
	{
		get
		{
			return this._Comment_Detail;
		}
		set
		{
			if ((this._Comment_Detail != value))
			{
				this.OnComment_DetailChanging(value);
				this.SendPropertyChanging();
				this._Comment_Detail = value;
				this.SendPropertyChanged("Comment_Detail");
				this.OnComment_DetailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_EventId", DbType="Int NOT NULL")]
	public int Comment_EventId
	{
		get
		{
			return this._Comment_EventId;
		}
		set
		{
			if ((this._Comment_EventId != value))
			{
				this.OnComment_EventIdChanging(value);
				this.SendPropertyChanging();
				this._Comment_EventId = value;
				this.SendPropertyChanged("Comment_EventId");
				this.OnComment_EventIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_Maker", DbType="Int NOT NULL")]
	public int Comment_Maker
	{
		get
		{
			return this._Comment_Maker;
		}
		set
		{
			if ((this._Comment_Maker != value))
			{
				this.OnComment_MakerChanging(value);
				this.SendPropertyChanging();
				this._Comment_Maker = value;
				this.SendPropertyChanged("Comment_Maker");
				this.OnComment_MakerChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment_PublishTime", DbType="DateTime NOT NULL")]
	public System.DateTime Comment_PublishTime
	{
		get
		{
			return this._Comment_PublishTime;
		}
		set
		{
			if ((this._Comment_PublishTime != value))
			{
				this.OnComment_PublishTimeChanging(value);
				this.SendPropertyChanging();
				this._Comment_PublishTime = value;
				this.SendPropertyChanged("Comment_PublishTime");
				this.OnComment_PublishTimeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
