#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Darili")]
public partial class PosterDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 可扩展性方法定义
  partial void OnCreated();
  partial void InsertEvent_Poster(Event_Poster instance);
  partial void UpdateEvent_Poster(Event_Poster instance);
  partial void DeleteEvent_Poster(Event_Poster instance);
  #endregion
	
	public PosterDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["416ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public PosterDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PosterDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PosterDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public PosterDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Event_Poster> Event_Poster
	{
		get
		{
			return this.GetTable<Event_Poster>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Event_Poster")]
public partial class Event_Poster : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Event_id;
	
	private System.Nullable<System.Guid> _poster;
	
	private System.Data.Linq.Binary _thumb_stream;
	
	private System.Nullable<System.Guid> _poster_thumb;
	
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEvent_idChanging(int value);
    partial void OnEvent_idChanged();
    partial void OnposterChanging(System.Nullable<System.Guid> value);
    partial void OnposterChanged();
    partial void Onthumb_streamChanging(System.Data.Linq.Binary value);
    partial void Onthumb_streamChanged();
    partial void Onposter_thumbChanging(System.Nullable<System.Guid> value);
    partial void Onposter_thumbChanged();
    #endregion
	
	public Event_Poster()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Event_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Event_id
	{
		get
		{
			return this._Event_id;
		}
		set
		{
			if ((this._Event_id != value))
			{
				this.OnEvent_idChanging(value);
				this.SendPropertyChanging();
				this._Event_id = value;
				this.SendPropertyChanged("Event_id");
				this.OnEvent_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poster", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> poster
	{
		get
		{
			return this._poster;
		}
		set
		{
			if ((this._poster != value))
			{
				this.OnposterChanging(value);
				this.SendPropertyChanging();
				this._poster = value;
				this.SendPropertyChanged("poster");
				this.OnposterChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thumb_stream", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary thumb_stream
	{
		get
		{
			return this._thumb_stream;
		}
		set
		{
			if ((this._thumb_stream != value))
			{
				this.Onthumb_streamChanging(value);
				this.SendPropertyChanging();
				this._thumb_stream = value;
				this.SendPropertyChanged("thumb_stream");
				this.Onthumb_streamChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_poster_thumb", DbType="UniqueIdentifier")]
	public System.Nullable<System.Guid> poster_thumb
	{
		get
		{
			return this._poster_thumb;
		}
		set
		{
			if ((this._poster_thumb != value))
			{
				this.Onposter_thumbChanging(value);
				this.SendPropertyChanging();
				this._poster_thumb = value;
				this.SendPropertyChanged("poster_thumb");
				this.Onposter_thumbChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
